development:
    cloudinary_cloud_name: jodlo
    cloudinary_api_key: 445562822693376
    cloudinary_api_secret: NsqSzk0aYt-jM6wg5p-YPxC6Ipo
    secret_key_base: 82c85638b167c184e823e8abc6d8048904dd124529c057125bc2a55d118e2d82e8bbe8fef5e4df84851427f2770f100b84ac126b46f8ff7a24f1eebd7d72f205
test:
    cloudinary_cloud_name: jodlo
    cloudinary_api_key: 445562822693376
    cloudinary_api_secret: NsqSzk0aYt-jM6wg5p-YPxC6Ipo
    secret_key_base: 82c85638b167c184e823e8abc6d8048904dd124529c057125bc2a55d118e2d82e8bbe8fef5e4df84851427f2770f100b84ac126b46f8ff7a24f1eebd7d72f205

production:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
